[package]
name = "advent-cli"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow = { workspace = true }
argh = { workspace = true }
curl = { workspace = true }
open = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
